# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ControlStock(object):
    def setupUi(self, ControlStock):
        ControlStock.setObjectName("ControlStock")
        ControlStock.resize(545, 635)
        self.gridLayout = QtWidgets.QGridLayout(ControlStock)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(ControlStock)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableVencimiento = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableVencimiento.setObjectName("tableVencimiento")
        self.tableVencimiento.setColumnCount(4)
        self.tableVencimiento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVencimiento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVencimiento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVencimiento.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVencimiento.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tableVencimiento)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ControlStock)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableResumen = QtWidgets.QTableWidget(self.groupBox)
        self.tableResumen.setObjectName("tableResumen")
        self.tableResumen.setColumnCount(3)
        self.tableResumen.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumen.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumen.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumen.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableResumen)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(ControlStock)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableRegistroVenta = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableRegistroVenta.setObjectName("tableRegistroVenta")
        self.tableRegistroVenta.setColumnCount(5)
        self.tableRegistroVenta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRegistroVenta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRegistroVenta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRegistroVenta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRegistroVenta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRegistroVenta.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.tableRegistroVenta)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(ControlStock)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableStockBajo = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableStockBajo.setObjectName("tableStockBajo")
        self.tableStockBajo.setColumnCount(3)
        self.tableStockBajo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStockBajo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStockBajo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStockBajo.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tableStockBajo)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)

        self.retranslateUi(ControlStock)
        QtCore.QMetaObject.connectSlotsByName(ControlStock)

    def retranslateUi(self, ControlStock):
        _translate = QtCore.QCoreApplication.translate
        ControlStock.setWindowTitle(_translate("ControlStock", "Control de Stock"))
        self.groupBox_3.setTitle(_translate("ControlStock", "Fechas de vencimiento próximas"))
        item = self.tableVencimiento.horizontalHeaderItem(0)
        item.setText(_translate("ControlStock", "Código"))
        item = self.tableVencimiento.horizontalHeaderItem(1)
        item.setText(_translate("ControlStock", "Producto"))
        item = self.tableVencimiento.horizontalHeaderItem(2)
        item.setText(_translate("ControlStock", "Cantidad"))
        item = self.tableVencimiento.horizontalHeaderItem(3)
        item.setText(_translate("ControlStock", "Fecha de vencimiento"))
        self.groupBox.setTitle(_translate("ControlStock", "Resumen"))
        item = self.tableResumen.horizontalHeaderItem(0)
        item.setText(_translate("ControlStock", "Vendedor"))
        item = self.tableResumen.horizontalHeaderItem(1)
        item.setText(_translate("ControlStock", "Total"))
        item = self.tableResumen.horizontalHeaderItem(2)
        item.setText(_translate("ControlStock", "Controlado"))
        self.groupBox_2.setTitle(_translate("ControlStock", "Historial de ventas"))
        item = self.tableRegistroVenta.horizontalHeaderItem(0)
        item.setText(_translate("ControlStock", "Vendedor"))
        item = self.tableRegistroVenta.horizontalHeaderItem(1)
        item.setText(_translate("ControlStock", "Producto"))
        item = self.tableRegistroVenta.horizontalHeaderItem(2)
        item.setText(_translate("ControlStock", "Cantidad"))
        item = self.tableRegistroVenta.horizontalHeaderItem(3)
        item.setText(_translate("ControlStock", "Precio unitario"))
        item = self.tableRegistroVenta.horizontalHeaderItem(4)
        item.setText(_translate("ControlStock", "Total"))
        self.groupBox_4.setTitle(_translate("ControlStock", "Stock bajo"))
        item = self.tableStockBajo.horizontalHeaderItem(0)
        item.setText(_translate("ControlStock", "Código"))
        item = self.tableStockBajo.horizontalHeaderItem(1)
        item.setText(_translate("ControlStock", "Producto"))
        item = self.tableStockBajo.horizontalHeaderItem(2)
        item.setText(_translate("ControlStock", "Cantidad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ControlStock = QtWidgets.QWidget()
    ui = Ui_ControlStock()
    ui.setupUi(ControlStock)
    ControlStock.show()
    sys.exit(app.exec_())

