# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.pushConsultar.setObjectName("pushConsultar")
        self.gridLayout.addWidget(self.pushConsultar, 1, 2, 1, 1)
        self.lineCodigo = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCodigo.sizePolicy().hasHeightForWidth())
        self.lineCodigo.setSizePolicy(sizePolicy)
        self.lineCodigo.setObjectName("lineCodigo")
        self.gridLayout.addWidget(self.lineCodigo, 1, 1, 1, 1)
        self.pushBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushBorrar.setObjectName("pushBorrar")
        self.gridLayout.addWidget(self.pushBorrar, 1, 3, 1, 1)
        self.tableStock = QtWidgets.QTableWidget(self.centralwidget)
        self.tableStock.setObjectName("tableStock")
        self.tableStock.setColumnCount(0)
        self.tableStock.setRowCount(0)
        self.gridLayout.addWidget(self.tableStock, 2, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 30))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuStock = QtWidgets.QMenu(self.menubar)
        self.menuStock.setObjectName("menuStock")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAgregar = QtWidgets.QAction(MainWindow)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionMarcas = QtWidgets.QAction(MainWindow)
        self.actionMarcas.setObjectName("actionMarcas")
        self.actionAcercaDe = QtWidgets.QAction(MainWindow)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        self.actionQuitar = QtWidgets.QAction(MainWindow)
        self.actionQuitar.setObjectName("actionQuitar")
        self.actionInformacion = QtWidgets.QAction(MainWindow)
        self.actionInformacion.setObjectName("actionInformacion")
        self.actionModificar = QtWidgets.QAction(MainWindow)
        self.actionModificar.setObjectName("actionModificar")
        self.actionMarcass = QtWidgets.QAction(MainWindow)
        self.actionMarcass.setObjectName("actionMarcass")
        self.actionControl = QtWidgets.QAction(MainWindow)
        self.actionControl.setObjectName("actionControl")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuStock.addAction(self.actionModificar)
        self.menuStock.addSeparator()
        self.menuStock.addAction(self.actionMarcass)
        self.menuStock.addSeparator()
        self.menuStock.addAction(self.actionControl)
        self.menuAcerca_de.addAction(self.actionAcercaDe)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineCodigo, self.pushConsultar)
        MainWindow.setTabOrder(self.pushConsultar, self.pushBorrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Control de stock"))
        self.label.setText(_translate("MainWindow", "Código:"))
        self.pushConsultar.setText(_translate("MainWindow", "Consultar"))
        self.pushBorrar.setText(_translate("MainWindow", "Borrar consulta"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuStock.setTitle(_translate("MainWindow", "Stock"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Alt+Q"))
        self.actionAgregar.setText(_translate("MainWindow", "Agregar"))
        self.actionAgregar.setShortcut(_translate("MainWindow", "Alt+R"))
        self.actionBuscar.setText(_translate("MainWindow", "Buscar"))
        self.actionMarcas.setText(_translate("MainWindow", "Marcas"))
        self.actionMarcas.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionAcercaDe.setText(_translate("MainWindow", "Acerca de..."))
        self.actionQuitar.setText(_translate("MainWindow", "Quitar"))
        self.actionQuitar.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actionInformacion.setText(_translate("MainWindow", "Información"))
        self.actionModificar.setText(_translate("MainWindow", "&Modificar"))
        self.actionModificar.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionMarcass.setText(_translate("MainWindow", "Marca&s"))
        self.actionMarcass.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionControl.setText(_translate("MainWindow", "&Control"))
        self.actionControl.setShortcut(_translate("MainWindow", "Alt+C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

