# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.pushConsultar.setObjectName("pushConsultar")
        self.gridLayout.addWidget(self.pushConsultar, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_2.addWidget(self.comboBox_5, 1, 4, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_2.addWidget(self.comboBox_6, 1, 5, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 4)
        self.pushBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushBorrar.setObjectName("pushBorrar")
        self.gridLayout.addWidget(self.pushBorrar, 1, 3, 1, 1)
        self.lineCodigo = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCodigo.sizePolicy().hasHeightForWidth())
        self.lineCodigo.setSizePolicy(sizePolicy)
        self.lineCodigo.setObjectName("lineCodigo")
        self.gridLayout.addWidget(self.lineCodigo, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableStock = QtWidgets.QTableWidget(self.groupBox)
        self.tableStock.setObjectName("tableStock")
        self.tableStock.setColumnCount(4)
        self.tableStock.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableStock)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 30))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuStock = QtWidgets.QMenu(self.menubar)
        self.menuStock.setObjectName("menuStock")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAgregar = QtWidgets.QAction(MainWindow)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionMarcas = QtWidgets.QAction(MainWindow)
        self.actionMarcas.setObjectName("actionMarcas")
        self.actionAcercaDe = QtWidgets.QAction(MainWindow)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        self.actionQuitar = QtWidgets.QAction(MainWindow)
        self.actionQuitar.setObjectName("actionQuitar")
        self.actionInformacion = QtWidgets.QAction(MainWindow)
        self.actionInformacion.setObjectName("actionInformacion")
        self.actionModificar = QtWidgets.QAction(MainWindow)
        self.actionModificar.setObjectName("actionModificar")
        self.actionMarcass = QtWidgets.QAction(MainWindow)
        self.actionMarcass.setObjectName("actionMarcass")
        self.actionControl = QtWidgets.QAction(MainWindow)
        self.actionControl.setObjectName("actionControl")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuStock.addAction(self.actionModificar)
        self.menuStock.addSeparator()
        self.menuStock.addAction(self.actionMarcass)
        self.menuStock.addSeparator()
        self.menuStock.addAction(self.actionControl)
        self.menuAcerca_de.addAction(self.actionAcercaDe)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineCodigo, self.pushConsultar)
        MainWindow.setTabOrder(self.pushConsultar, self.pushBorrar)
        MainWindow.setTabOrder(self.pushBorrar, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.tableStock)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Control de stock"))
        self.pushConsultar.setText(_translate("MainWindow", "Consultar"))
        self.label.setText(_translate("MainWindow", "Código:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Venta"))
        self.label_2.setText(_translate("MainWindow", "Código"))
        self.label_7.setText(_translate("MainWindow", "Vendedor"))
        self.label_6.setText(_translate("MainWindow", "Total"))
        self.label_5.setText(_translate("MainWindow", "Cantidad"))
        self.label_3.setText(_translate("MainWindow", "Producto"))
        self.label_4.setText(_translate("MainWindow", "Precio unitario"))
        self.pushBorrar.setText(_translate("MainWindow", "Borrar consulta"))
        self.groupBox.setTitle(_translate("MainWindow", "Historial de ventas"))
        item = self.tableStock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableStock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.tableStock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marca"))
        item = self.tableStock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precio"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuStock.setTitle(_translate("MainWindow", "Stock"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Alt+Q"))
        self.actionAgregar.setText(_translate("MainWindow", "Agregar"))
        self.actionAgregar.setShortcut(_translate("MainWindow", "Alt+R"))
        self.actionBuscar.setText(_translate("MainWindow", "Buscar"))
        self.actionMarcas.setText(_translate("MainWindow", "Marcas"))
        self.actionMarcas.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionAcercaDe.setText(_translate("MainWindow", "Acerca de..."))
        self.actionQuitar.setText(_translate("MainWindow", "Quitar"))
        self.actionQuitar.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actionInformacion.setText(_translate("MainWindow", "Información"))
        self.actionModificar.setText(_translate("MainWindow", "&Modificar"))
        self.actionModificar.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionMarcass.setText(_translate("MainWindow", "Marca&s"))
        self.actionMarcass.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionControl.setText(_translate("MainWindow", "&Control"))
        self.actionControl.setShortcut(_translate("MainWindow", "Alt+C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

